name: execprompt
description: ExecPrompt â€” Premium Ollama client with CyberTerm aesthetic
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  drift: ^2.14.0
  file_picker: '>=8.0.0 <8.1.0'
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  highlight: ^0.7.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  markdown: ^7.0.0
  markdown_widget: ^2.3.2+6
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  url_launcher: ^6.2.2
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
